lib/worklog_web/router.ex
defmodule TodayWeb.Router do
  use TodayWeb, :router
  use Pow.Phoenix.Router
  use Pow.Extension.Phoenix.Router,
  extensions: [PowResetPassword, PowEmailConfirmation]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TodayWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TodayWeb.AssignUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :authenticated do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :admin do
  end

  scope "/" do
    pipe_through :browser
    pow_routes()
    pow_extension_routes()
  end

  scope "/", TodayWeb do
    pipe_through [:browser, :authenticated]
    live "/", DashboardLive, :index
  end

  scope "/worklogs", TodayWeb do
    pipe_through [:browser, :authenticated]
    live "/", WorklogsLive, :index
    live "/new", WorklogsLive, :new
    live "/search", WorklogsLive, :search
    live "/edit/:id", WorklogsLive, :edit
  end

  scope "/tags", TodayWeb do
    pipe_through [:browser, :authenticated]
    live "/", TagsLive, :index
    live "/new", TagsLive, :new
    live "/search", TagsLive, :search
  end

  scope "/users", TodayWeb do
    pipe_through [:browser, :authenticated, :admin]
    live "/", UsersLive, :index
    live "/new", UsersLive, :new
    live "/edit", UsersLive, :edit
    live "/search", UsersLive, :search
  end

  # Other scopes may use custom stacks.
  # scope "/api", TodayWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TodayWeb.Telemetry
    end
  end
end

lib/worklog_web/views/layout_view.ex
defmodule TodayWeb.LayoutView do
  use TodayWeb, :view
end

lib/worklog_web/templates/layout/app.html.eex
<main role="main">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/worklog_web/templates/layout/live.html.leex
<main role="main">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/worklog_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Today" %>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="icon" type="image/svg+xml" href="<%= Routes.static_path(@conn, "/images/noun_diary_2908670.svg") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
  </head>
  <body>
    <header x-data="{ mobileMenuOpen : false }" class="flex flex-wrap flex-row justify-between md:items-center md:space-x-4 bg-blue-900 py-6 px-6 relative">
      <%= live_redirect "Today", to: Routes.dashboard_path(@conn, :index), class: "text-gray-100 hover:underline h-6 md:h-8" %>
      <button @click="mobileMenuOpen = !mobileMenuOpen" class="inline-block md:hidden w-8 h-8 bg-blue-900 text-gray-300 p-1">
        <svg fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
      </button>
      <nav class="md:relative top-16 left-0 md:top-16 z-20 md:flex flex-col md:flex-row md:space-x-6 font-semibold w-full md:w-auto bg-gray-600 shadow-md rounded-lg md:rounded-none md:shadow-none md:bg-transparent p-6 pt-0 md:p-0"
      :class="{ 'flex' : mobileMenuOpen , 'hidden' : !mobileMenuOpen}" @click.away="mobileMenuOpen = false">
        <%= if Pow.Plug.current_user(@conn) do %>
          <a><%= live_redirect "Dashboard", to: Routes.dashboard_path(@conn, :index), class: "text-gray-100 hover:underline" %></a>
          <a><%= live_redirect "Worklogs", to: Routes.worklogs_path(@conn, :index), class: "text-gray-100 hover:underline" %></a>
          <a><%= live_redirect "Tags", to: Routes.tags_path(@conn, :index), class: "text-gray-100 hover:underline" %></a>
          <a><%= live_redirect "Users", to: Routes.users_path(@conn, :index), class: "text-gray-100 hover:underline" %></a>
          <a><%= link "Sign Out", to: Routes.pow_session_path(@conn, :delete), method: :delete, class: "text-gray-100 hover:underline" %></a>
        <% else %>
          <a><%= link "Sign In", to: Routes.pow_session_path(@conn, :new), class: "text-gray-100 hover:underline" %></a>
        <% end %>
      </nav>
    </header>

    <%= @inner_content %>
  </body>
</html>